import { getMeta, getCountries } from "@/lib/data";

export const metadata = { title: "Data and scoring code", alternates: { canonical: "/data" } };

export default function DataPage() {
  const meta = getMeta();
  const n = getCountries().length;
  return (
    <div className="mx-auto max-w-2xl py-12">
      <h1 className="serif text-3xl font-black">Data &amp; scoring code</h1>
      <p className="mt-4 text-[15px] leading-relaxed text-fg2">
        Every published score can be traced from the source data through the scoring code to the
        downloadable output. You can inspect each part and run the calculation yourself.
      </p>

      <div className="card mt-6 p-5">
        <div className="mono text-[12px] text-fg3">HOW A SCORE IS PRODUCED</div>
        <div className="mt-3 space-y-2 text-[13px]">
          <div className="flex gap-3">
            <span className="mono text-primary">1</span>
            <span>
              <b>Public scoring code:</b> the fixed formula, written in Python. The same inputs
              produce the same result.
            </span>
          </div>
          <div className="flex gap-3">
            <span className="mono text-primary">2</span>
            <span>
              <b>Public source data:</b> governance and development data from the World Bank, V-Dem,
              Maddison, Transparency International, WIPO, the Harvard Atlas, and the Fund for Peace.
            </span>
          </div>
          <div className="flex gap-3">
            <span className="mono text-primary">3</span>
            <span>
              <b>Published outputs:</b> the dataset below, regenerated by running the scoring code over the
              data.
            </span>
          </div>
        </div>
      </div>

      <div className="mt-6 grid gap-3 sm:grid-cols-2">
        <a
          href="/data/countries.json"
          className="card lift flex flex-col gap-1 p-4"
        >
          <span className="text-[14px] font-medium">Full dataset (JSON)</span>
          <span className="mono text-[11px] text-fg3">{n} countries · pillar scores · diagnostics</span>
        </a>
        <a
          href="https://github.com/Rsan0948/universalsystemgrade"
          className="card lift flex flex-col gap-1 p-4"
        >
          <span className="text-[14px] font-medium">Scoring source code</span>
          <span className="mono text-[11px] text-fg3">view and download the public repository</span>
        </a>
      </div>

      <p className="mono mt-6 text-[11px] text-fg3">
        Built {meta.built} · scoring version {meta.engine} · {meta.data_vintage}. Project data: CC BY-NC 4.0.
      </p>
      <p className="mt-2 text-[12px] text-fg3">
        {meta.note} Third-party source data remains subject to its provider&apos;s terms.
      </p>
    </div>
  );
}
