import { getMeta, getCountries } from "@/lib/data";

export const metadata = { title: "Data and engine | Modernization Index" };

export default function DataPage() {
  const meta = getMeta();
  const n = getCountries().length;
  return (
    <div className="mx-auto max-w-2xl py-12">
      <h1 className="serif text-3xl font-black">Data &amp; engine</h1>
      <p className="mt-4 text-[15px] leading-relaxed text-fg2">
        Every published score can be traced from the source data through the scoring code to the
        downloadable output. You can inspect each part and run the calculation yourself.
      </p>

      <div className="card mt-6 p-5">
        <div className="mono text-[12px] text-fg3">THE REPRODUCIBLE CHAIN</div>
        <div className="mt-3 space-y-2 text-[13px]">
          <div className="flex gap-3">
            <span className="mono text-primary">1</span>
            <span>
              <b>Open-source engine:</b> the fixed scoring formula, written in Python. The same inputs
              produce the same result.
            </span>
          </div>
          <div className="flex gap-3">
            <span className="mono text-primary">2</span>
            <span>
              <b>Public source data:</b> World Bank WGI/WDI, V-Dem, Maddison, Transparency
              International, WIPO, Harvard Atlas, Fund for Peace. All citable, all public.
            </span>
          </div>
          <div className="flex gap-3">
            <span className="mono text-primary">3</span>
            <span>
              <b>Published outputs:</b> the dataset below, regenerated by running the engine over the
              data.
            </span>
          </div>
        </div>
      </div>

      <div className="mt-6 grid gap-3 sm:grid-cols-2">
        <a
          href="/data/countries.json"
          className="card lift flex flex-col gap-1 p-4"
        >
          <span className="text-[14px] font-medium">Full dataset (JSON)</span>
          <span className="mono text-[11px] text-fg3">{n} countries · all pillars · all classifiers</span>
        </a>
        <a
          href="https://github.com/Rsan0948/universalsystemgrade"
          className="card lift flex flex-col gap-1 p-4"
        >
          <span className="text-[14px] font-medium">Engine source code</span>
          <span className="mono text-[11px] text-fg3">view and download the public repository</span>
        </a>
      </div>

      <p className="mono mt-6 text-[11px] text-fg3">
        Built {meta.built} · engine {meta.engine} · {meta.data_vintage}. License: CC BY 4.0.
      </p>
      <p className="mt-2 text-[12px] text-fg3">{meta.note}</p>
    </div>
  );
}
